name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
jobs:
    test_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: '22.8.0'

            - name: Install dependencies
              run: yarn ci
            - name: Run tests
              run: yarn test
            - name: Build
              run: yarn build
